name: 'Repo Metadata Sync'
description: 'Github Action to sync repo metadata (description, url, and topics) from code to repo'
author: 'kbrashears5'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  TYPE:
    description: 'Type of repo (i.e. npm, nuget, etc. - see README for full list)'
    required: true
  PATH:
    description: 'Relative file path to the repos metadata file'
    required: true
  TOKEN:
    description: "Personal access token with Repo privileges"
    required: true
  GIT_EMAIL:
    description: 'Email to use for Git'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  GIT_USERNAME:
    description: 'Username to use for Git'
    required: false
    default: 'github-actions[bot]'

runs:
  using: 'docker'
  image: 'Dockerfile'